### ISSUE TITLE
String in DB argument cannot contain a comma

### ISSUE THREAD

**Issue by danya02** [pamoroso/suite8080#3]
The code that splits the arguments for a `DB` directive blindly splits the string by commas, even if the comma is inside of a string:

https://github.com/pamoroso/suite8080/blob/e6f5771a581e94a94737e458eb3f6670e4805084/suite8080/asm80.py#L1055-L1063

This means that declaring a string of text containing a comma can't be done directly:

```asm
; this will fail
text: DB 'Hello, World!'
```

As a workaround, the ASCII comma has the code `2C` in hex, so you can split your string on that and insert it on its own.

```asm
; hacky workaround
text: DB 'Hello', 2Ch, ' World!'
```

**Comment by pamoroso** [comment]
Yes, thanks, the parser is fragile and I'll eventually rewrite it. I had indeed [documented a similar workaround](https://suite8080.readthedocs.io/en/latest/usage.html#limitations-and-issues) for strings containing commas.
