### ISSUE TITLE
More styles of numeric base notation?

### ISSUE THREAD

**Issue by danya02** [pamoroso/suite8080#4]
The traditional way to write hex numbers in Intel assemblers is with the `h` suffix: `AB12h`, `C8h`.
However, there are many different ways to write such numbers; the one I'm most familiar with is the C-style `0x` prefix: `0xAB12`, `0xC8`.

The [Netwide Assembler](https://www.nasm.us/xdoc/2.15.05/html/nasmdoc3.html#section-3.4.1) accepts a whole 4 ways of annotating numbers as hex: `C8h`, `$0C8`, `0xC8` and `0hC8`. Are there any plans to add such options here?

**Comment by pamoroso** [comment]
Despite the convenience, I don't plan to add C-style or other numeric base notations as traditional CP/M and early 8080 assemblers work with the `h` suffix. This is enough for my needs.

**Comment by danya02** [comment]
Okay, I think I'll try implementing that in a fork. Also, [sorry for annoying you with the suggestions](https://github.com/pamoroso/suite8080/commit/0fb041c43e6438884d4d40bcd93e84ff22de4ed8).

**Comment by pamoroso** [comment]
I'm sorry if those words sounded harsh. Although I added that wording to `README.md` after you opened the recent issues, those words weren't addressed specifically to you. The issues were only an occasion for a clarification I was meaning to post for a long time. I appreciate your feedback, but the changes you suggest aren't in the direction I'm planning for Suite8080.
