### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'FCB+32'

### ISSUE THREAD

**Issue by ravn** [pamoroso/suite8080#5]
The following line gives the error in the title

    FCBCR	EQU	FCB+32	;CURRENT RECORD LOCATION

FCB was defined in the previous line as 

    FCB	EQU	005CH	;DEFAULT FCB LOCATION

My guess would be that you do not expect an expression here.

**Comment by pamoroso** [comment]
This is indeed the case, `asm80` doesn't support expressions. Suite8080 is unfortunately just a toy project to teach me 8080 Assembly, tools so it's not designed to handle the full syntax of typical 8080 assemblers.
