### ISSUE TITLE
Support of local labels

### ISSUE THREAD

**Issue by afiskon** [pamoroso/suite8080#6]
Firstly, many thanks for the great project. Secondly, I apologize if GitHub Issues is the wrong place for feature requests.

It would be convenient if suite8080 supported local labels, for instance:

```
@@:          ; local label (1)
   nop
   jmp @B ; jump back to (1)
   nop
   jmp @F ; jump forward to (2)
   nop
@@:         ; local label (2)
  nop
```

The particular syntax is not important. Different assemblers do this differently.

**Comment by pamoroso** [comment]
Thanks your kind words, I'm glad you enjoy Suite8080. However, I was actually meaning to archive this repo as I no longer use Python, so I won't enchance or maintain Suite8080.

If you need a good 8080 assembler I recommend [zasm](https://k1.spdns.de/Develop/Projects/zasm/Distributions/) which, although it's a Z80 assembler, fully supports 8080, is easy to use, and provides several useful directives.

**Comment by afiskon** [comment]
Right, but I wanted a good 8080 assembler **written in Python** :) It can be installed on MacOS with a single command which I find very convenient. (You may find interesting that I'm using your compiler for developing for a very old soviet PC called [Iskra 1080 Tartu](https://alemorf.github.io/retro_computers/computer.html?id=Iskra_1080_Tartu).)

OK then, maybe I will find time implementing local labels myself one day :)

**Comment by pamoroso** [comment]
For Python solutions you may have a look at these 8080 assemblers:

* [8080-assembler](https://github.com/gt-retro-computing/8080-assembler)
* [dis_8080](https://github.com/lechien73/dis_8080)

Developing for the Iskra seems like a cool retrocomputing project, best wishes for your work.

**Comment by afiskon** [comment]
TWIMC I created a fork where I fixed this: https://github.com/afiskon/suite8080
